INSERT INTO USERS(USERNAME, BIO, EMAIL, PASSWORD, TITLE)
VALUES('TrueReviewAdmin01', 'Parker Nelson - Co-Founder', 'pk.elliott11@me.com', 'parkers password', NULL);



INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 1, "Barbie", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 2, "Batman & Robin", 1);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 3, "Batman Begins", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 4, "Batman Returns", 0.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 5, "Batman v Superman: Dawn of Justice", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 6, "Beautiful Boy", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 7, "Beauty and the Beast", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 8, "Bedtime Stories", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 9, "Bee Movie", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 10, "Big Hero 6", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 11, "Bird Box", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 12, "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 13, "Black Panther", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 14, "Black Panther: Wakanda Forever", 1);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 15, "Black Swan", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 16, "Black Widow", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 17, "Blade Runner 2049", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 18, "Bolt", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 19, "Boundin'", 2.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 20, "Brave", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 21, "Bumblebee", 1);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 22, "Captain America: Civil War", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 23, "Captain America: The First Avenger", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 24, "Captain America: The Winter Soldier", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 25, "Captain Marvel", 1);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 26, "Cars", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 27, "Cars 2", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 28, "Cars 3", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 29, "Casablanca", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 30, "Casino Royale", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 31, "Charlie and the Chocolate Factory", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 32, "Civil War", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 33, "Coco", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 34, "Creed", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 35, "Creed II", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 36, "Creed III", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 37, "Dallas Buyers Club", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 38, "Deadpool", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 39, "Deadpool & Wolverine", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 40, "Deadpool 2", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 41, "Demon Slayer: Kimetsu no Yaiba Infinity Castle", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 42, "Despicable Me", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 43, "Doctor Strange", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 44, "Doctor Strange in the Multiverse of Madness", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 45, "Don't Worry Darling", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 46, "Dune", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 47, "Dune: Part Two", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 48, "Dungeons & Dragons: Honor Among Thieves", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 49, "Dunkirk", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 50, "Edge of Tomorrow", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 51, "Elf", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 52, "Elvis", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 53, "Emilia Pérez", 0.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 54, "Encanto", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 55, "Eternals", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 56, "Everyone's Hero", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 57, "Everything Everywhere All at Once", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 58, "Fantastic Beasts and Where to Find Them", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 59, "Fantastic Four", 1);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 60, "Fantastic Four", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 61, "Fantastic Four: Rise of the Silver Surfer", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 62, "Ferris Bueller's Day Off", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 63, "Finding Nemo", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 64, "Five Feet Apart", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 65, "Flushed Away", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 66, "For the Birds", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 67, "Free Guy", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 68, "Friends with Benefits", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 69, "Frozen", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 70, "Furiosa: A Mad Max Saga", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 71, "Fury", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 72, "G-Force", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 73, "G.I. Joe: The Rise of Cobra", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 74, "Gladiator", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 75, "Gladiator II", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 76, "Godzilla", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 77, "Godzilla Minus One", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 78, "Godzilla: King of the Monsters", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 79, "Good Time", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 80, "Good Will Hunting", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 81, "Gravity", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 82, "Green Lantern", 0.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 83, "Grown Ups", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 84, "Guardians of the Galaxy", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 85, "Guardians of the Galaxy Vol. 2", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 86, "Guardians of the Galaxy Vol. 3", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 87, "Happy Gilmore", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 88, "Harry Potter and the Chamber of Secrets", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 89, "Harry Potter and the Deathly Hallows: Part 1", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 90, "Harry Potter and the Deathly Hallows: Part 2", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 91, "Harry Potter and the Goblet of Fire", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 92, "Harry Potter and the Half-Blood Prince", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 93, "Harry Potter and the Order of the Phoenix", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 94, "Harry Potter and the Philosopher's Stone", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 95, "Harry Potter and the Prisoner of Azkaban", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 96, "Her", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 97, "High School Musical", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 98, "High School Musical 2", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 99, "High School Musical 3: Senior Year", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 100, "Hitch", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 101, "Home Alone", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 102, "Horton Hears a Who!", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 103, "Hot Rod", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 104, "How to Train Your Dragon", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 105, "Ice Age", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 106, "Ice Age: The Meltdown", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 107, "Inception", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 108, "Incredibles 2", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 109, "Inside Out", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 110, "Inside Out 2", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 111, "Insurgent", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 112, "Interstellar", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 113, "Iron Man", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 114, "Iron Man 2", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 115, "Iron Man 3", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 116, "It", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 117, "It Chapter Two", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 118, "It Ends with Us", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 119, "It Follows", 1);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 120, "John Carter", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 121, "John Wick", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 122, "Joker", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 123, "Joker: Folie à Deux", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 124, "Jurassic World", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 125, "Jurassic World: Fallen Kingdom", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 126, "Justice League", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 127, "Killers of the Flower Moon", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 128, "Kingdom of the Planet of the Apes", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 129, "Knives Out", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 130, "Kong: Skull Island", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 131, "KPop Demon Hunters", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 132, "Kung Fu Panda", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 133, "La La Land", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 134, "Lava", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 135, "Lemony Snicket's A Series of Unfortunate Events", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 136, "Logan", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 137, "Luca", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 138, "Mad Max: Fury Road", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 139, "Madagascar", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 140, "Madagascar 3: Europe's Most Wanted", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 141, "Madagascar: Escape 2 Africa", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 142, "Man of Steel", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 143, "Manchester by the Sea", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 144, "Maze Runner: The Death Cure", 2.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 145, "Maze Runner: The Scorch Trials", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 146, "Mean Girls", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 147, "Meet the Parents", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 148, "Meet the Robinsons", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 149, "Megalopolis", 0.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 150, "Megamind", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 151, "Memento", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 152, "Mickey 17", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 153, "Moana", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 154, "Moneyball", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 155, "Monster House", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 156, "Monsters University", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 157, "Monsters, Inc.", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 158, "Mulan", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 159, "Nacho Libre", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 160, "Napoleon Dynamite", 2.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 161, "Ne Zha 2", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 162, "Night at the Museum", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 163, "Night at the Museum: Battle of the Smithsonian", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 164, "Now You See Me", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 165, "Once Upon a Time... in Hollywood", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 166, "One Battle After Another", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 167, "One Man Band", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 168, "Oppenheimer", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 169, "Over the Hedge", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 170, "Pacific Rim", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 171, "Pan's Labyrinth", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 172, "Parasite", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 173, "Paul Blart: Mall Cop", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 174, "Paul Blart: Mall Cop 2", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 175, "Pirates of the Caribbean: At World's End", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 176, "Pirates of the Caribbean: Dead Man's Chest", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 177, "Pirates of the Caribbean: Dead Men Tell No Tales", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 178, "Pirates of the Caribbean: On Stranger Tides", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 179, "Pirates of the Caribbean: The Curse of the Black Pearl", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 180, "Pitch Perfect", 1);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 181, "Prince of Persia: The Sands of Time", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 182, "Princess Mononoke", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 183, "Prisoners", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 184, "Psycho", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 185, "Puss in Boots: The Last Wish", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 186, "Quantum of Solace", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 187, "Radio", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 188, "Rampage", 2.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 189, "Ratatouille", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 190, "Ready Player One", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 191, "Real Steel", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 192, "Remember the Titans", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 193, "Return of the Jedi", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 194, "Ricky Stanicky", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 195, "Rio", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 196, "Rio 2", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 197, "Road House", 2.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 198, "Rogue One: A Star Wars Story", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 199, "Saltburn", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 200, "Se7en", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 201, "Shang-Chi and the Legend of the Ten Rings", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 202, "Shark Tale", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 203, "Shazam!", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 204, "Sherlock Holmes", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 205, "Shrek", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 206, "Shrek 2", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 207, "Shrek Forever After", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 208, "Shutter Island", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 209, "Silence", 2.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 210, "Sinners", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 211, "Sky High", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 212, "Solo: A Star Wars Story", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 213, "Soul", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 214, "Southpaw", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 215, "Spider-Man", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 216, "Spider-Man 2", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 217, "Spider-Man 3", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 218, "Spider-Man: Across the Spider-Verse", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 219, "Spider-Man: Far From Home", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 220, "Spider-Man: Homecoming", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 221, "Spider-Man: Into the Spider-Verse", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 222, "Spider-Man: No Way Home", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 223, "Split", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 224, "Star Wars", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 225, "Star Wars: Episode I – The Phantom Menace", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 226, "Star Wars: Episode II – Attack of the Clones", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 227, "Star Wars: Episode III – Revenge of the Sith", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 228, "Star Wars: The Clone Wars", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 229, "Star Wars: The Force Awakens", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 230, "Star Wars: The Last Jedi", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 231, "Star Wars: The Rise of Skywalker", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 232, "Suicide Squad", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 233, "Sully", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 234, "Superman", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 235, "Surf's Up", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 236, "Tangled", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 237, "Teenage Mutant Ninja Turtles", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 238, "Tenet", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 239, "The Adventures of Sharkboy and Lavagirl", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 240, "The Adventures of Tintin", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 241, "The Amazing Spider-Man", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 242, "The Amazing Spider-Man 2", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 243, "The Avengers", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 244, "The Banshees of Inisherin", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 245, "The Batman", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 246, "The Cat in the Hat", 2.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 247, "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 248, "The Croods", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 249, "The Dark Knight", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 250, "The Dark Knight Rises", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 251, "The Departed", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 252, "The Empire Strikes Back", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 253, "The Fall Guy", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 254, "The Fantastic Four: First Steps", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 255, "The Fighter", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 256, "The Founder", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 257, "The Fugitive", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 258, "The Giver", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 259, "The Good Dinosaur", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 260, "The Great Gatsby", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 261, "The Greatest Showman", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 262, "The Hangover", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 263, "The Hobbit: An Unexpected Journey", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 264, "The Hobbit: The Battle of the Five Armies", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 265, "The Hobbit: The Desolation of Smaug", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 266, "The Hunger Games", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 267, "The Hunger Games: Catching Fire", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 268, "The Hunger Games: Mockingjay – Part 1", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 269, "The Hunger Games: Mockingjay – Part 2", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 270, "The Hunger Games: The Ballad of Songbirds & Snakes", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 271, "The Incredible Hulk", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 272, "The Incredibles", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 273, "The Iron Claw", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 274, "The Lego Batman Movie", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 275, "The Lego Movie", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 276, "The Lion King", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 277, "The Lone Ranger", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 278, "The Lorax", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 279, "The Lord of the Rings: The Fellowship of the Ring", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 280, "The Lord of the Rings: The Return of the King", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 281, "The Lord of the Rings: The Two Towers", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 282, "The Martian", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 283, "The Mask", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 284, "The Maze Runner", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 285, "The Northman", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 286, "The Notebook", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 287, "The Perks of Being a Wallflower", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 288, "The Polar Express", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 289, "The Prestige", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 290, "The Pursuit of Happyness", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 291, "The Revenant", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 292, "The Social Network", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 293, "The Suicide Squad", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 294, "The Super Mario Bros. Movie", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 295, "The Tale of Despereaux", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 296, "The Town", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 297, "The Upside", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 298, "The Whale", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 299, "The Wild Robot", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 300, "The Wizard of Oz", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 301, "The Wolf of Wall Street", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 302, "Thor", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 303, "Thor: Love and Thunder", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 304, "Thor: Ragnarok", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 305, "Thor: The Dark World", 1);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 306, "tick, tick... BOOM!", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 307, "Tooth Fairy", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 308, "Top Gun: Maverick", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 309, "Toy Story", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 310, "Toy Story 2", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 311, "Toy Story 3", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 312, "Toy Story 4", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 313, "Transformers", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 314, "Transformers: Age of Extinction", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 315, "Transformers: Dark of the Moon", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 316, "Transformers: Revenge of the Fallen", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 317, "Transformers: The Last Knight", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 318, "Twilight", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 319, "Unbroken", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 320, "Uncut Gems", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 321, "Up", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 322, "Venom", 3);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 323, "WALL·E", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 324, "War for the Planet of the Apes", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 325, "Warrior", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 326, "We Live in Time", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 327, "Where the Wild Things Are", 2);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 328, "Whiplash", 5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 329, "Wicked", 3.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 330, "Wonder Woman", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 331, "Wonka", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 332, "World War Z", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 333, "Wreck-It Ralph", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 334, "Zack Snyder's Justice League", 4.5);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 335, "Zodiac", 4);
INSERT INTO watched_list(user_id, movie_id, title, rating) VALUES (1, 336, "Zootopia", 4);